"use strict";
const str="teSt";
const arr=[1,2,4];
console.log(arr.length);
console.log(str.toLowerCase());
const fruit="Some fruit";
console.log(fruit.indexOf("q"));
console.log(fruit.slice(5));
console.log(fruit.substring(5));
console.log(fruit.substr(5,6));